#!/bin/bash
# iOS Development Setup Script for OrthoSense
# Fully automatic setup - detects Team ID and generates Bundle ID

set -e

# Set to 1 for interactive mode, 0 for fully automatic
INTERACTIVE_MODE=0

FLUTTER_DIR="ios/Flutter"
CONFIG_FILE="$FLUTTER_DIR/Developer.xcconfig"

echo "🍎 OrthoSense iOS Development Setup"
echo "===================================="
echo ""

# Check if already configured
if [ -f "$CONFIG_FILE" ]; then
    if [ "$INTERACTIVE_MODE" -eq 1 ]; then
        echo "⚠️  Developer.xcconfig already exists."
        read -p "Do you want to reconfigure it? (y/N): " -n 1 -r
        echo
        if [[ ! $REPLY =~ ^[Yy]$ ]]; then
            echo "ℹ️  Keeping existing configuration."
            exit 0
        fi
    else
        echo "⚠️  Developer.xcconfig already exists. Recreating..."
    fi
fi

# Auto-detect Team ID
echo "🔍 Auto-detecting Apple Development Team ID..."
DETECTED_TEAM_ID=""

# Try to get from security keychain
TEAM_IDS=$(security find-identity -v -p codesigning 2>/dev/null | grep "Apple Development" | sed -n 's/.*(\([A-Z0-9]\{10\}\)).*/\1/p' | sort -u)

if [ ! -z "$TEAM_IDS" ]; then
    # Get first Team ID
    DETECTED_TEAM_ID=$(echo "$TEAM_IDS" | head -n 1)
    echo "✅ Found Team ID: $DETECTED_TEAM_ID"
fi

# Get Team ID (with auto-detected as default)
echo ""
echo "📋 Step 1: Apple Development Team ID"
echo ""
if [ -z "$DETECTED_TEAM_ID" ]; then
    if [ "$INTERACTIVE_MODE" -eq 1 ]; then
        echo "ℹ️  Could not auto-detect Team ID."
        echo "Find your Team ID in Xcode → Settings (⌘,) → Accounts → Your Team"
        echo ""
        read -p "Enter your Apple Development Team ID: " TEAM_ID
    else
        echo "❌ Error: Could not auto-detect Team ID."
        echo "Please run with INTERACTIVE_MODE=1 or add Team ID manually to Developer.xcconfig"
        exit 1
    fi
else
    if [ "$INTERACTIVE_MODE" -eq 1 ]; then
        read -p "Enter your Apple Development Team ID [$DETECTED_TEAM_ID]: " TEAM_ID
        TEAM_ID=${TEAM_ID:-$DETECTED_TEAM_ID}
    else
        TEAM_ID=$DETECTED_TEAM_ID
        echo "✅ Using detected Team ID: $TEAM_ID"
    fi
fi

if [ -z "$TEAM_ID" ]; then
    echo "❌ Error: Team ID cannot be empty"
    exit 1
fi

# Validate Team ID format (should be 10 alphanumeric characters)
if ! [[ "$TEAM_ID" =~ ^[A-Z0-9]{10}$ ]]; then
    if [ "$INTERACTIVE_MODE" -eq 1 ]; then
        echo "⚠️  Warning: Team ID format seems unusual (expected 10 uppercase alphanumeric characters)"
        read -p "Continue anyway? (y/N): " -n 1 -r
        echo
        if [[ ! $REPLY =~ ^[Yy]$ ]]; then
            exit 1
        fi
    else
        echo "⚠️  Warning: Team ID format seems unusual, but continuing..."
    fi
fi

# Auto-generate Bundle ID
echo ""
echo "📦 Step 2: Bundle Identifier"
echo ""

# Try to get username from git config or system
GIT_NAME=$(git config user.name 2>/dev/null | tr '[:upper:]' '[:lower:]' | tr -cd '[:alnum:]' | head -c 20)
if [ -z "$GIT_NAME" ]; then
    GIT_NAME=$(whoami | tr '[:upper:]' '[:lower:]' | tr -cd '[:alnum:]')
fi

SUGGESTED_BUNDLE_ID="com.${GIT_NAME}.orthosense"

echo "Suggested Bundle ID based on your username: $SUGGESTED_BUNDLE_ID"
echo ""
echo "Other examples:"
echo "  - com.yourname.orthosense"
echo "  - com.companyname.orthosense"
echo ""

if [ "$INTERACTIVE_MODE" -eq 1 ]; then
    read -p "Enter your Bundle Identifier [$SUGGESTED_BUNDLE_ID]: " BUNDLE_ID
    BUNDLE_ID=${BUNDLE_ID:-$SUGGESTED_BUNDLE_ID}
else
    BUNDLE_ID=$SUGGESTED_BUNDLE_ID
    echo "✅ Using generated Bundle ID: $BUNDLE_ID"
fi

if [ -z "$BUNDLE_ID" ]; then
    echo "❌ Error: Bundle ID cannot be empty"
    exit 1
fi

# Validate Bundle ID format
if ! [[ "$BUNDLE_ID" =~ ^[a-zA-Z0-9.-]+$ ]]; then
    echo "❌ Error: Invalid Bundle ID format (should contain only letters, numbers, dots, and hyphens)"
    exit 1
fi

# Create configuration file
echo ""
echo "🔧 Creating Developer.xcconfig..."

cat > "$CONFIG_FILE" << EOF
// Local developer settings - DO NOT COMMIT
// This file is gitignored and should be created by each developer
// Generated by scripts/ios-setup.sh

// Your Apple Development Team ID (find it in Xcode → Settings → Accounts → Your Team)
DEVELOPMENT_TEAM=$TEAM_ID

// Override bundle identifier for local development
// Use a unique bundle ID that doesn't conflict with others
PRODUCT_BUNDLE_IDENTIFIER=$BUNDLE_ID
EOF

echo "✅ Configuration saved to: $CONFIG_FILE"
echo ""

# Summary
echo "📝 Configuration Summary:"
echo "  Team ID: $TEAM_ID"
echo "  Bundle ID: $BUNDLE_ID"
echo ""

# Next steps
echo "🚀 Next Steps:"
echo "  1. Run: flutter clean"
echo "  2. Run: flutter pub get"
echo "  3. Run: flutter run --release"
echo ""
echo "✨ Setup complete!"
